t = Time.utc_now()
IO.inspect(t)
IO.inspect(t.hour)
IO.inspect(t.minute)
IO.inspect(t.second)
IO.inspect(t.microsecond)
d = Date.utc_today()
IO.inspect(d.year)
IO.inspect(d.month)
IO.inspect(d.day)
dt = DateTime.utc_now()
IO.inspect(dt.year)
Enum.each(1..10, fn -> IO.puts("Hello") end)
